services:
  - type: web
    name: ebay-kleinanzeigen-api
    env: docker
    dockerfilePath: ./Dockerfile
    numInstances: 1
    healthCheckPath: /
    plan: free
    envVars:
      - key: PORT
        value: 8000
    disk:
      name: kleinanzeigen-data
      mountPath: /data
      sizeGB: 1 